{{- if .Values.settings.egress_aws_enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: metadataservice
spec:
  addresses:
  - 169.254.169.254/32
  hosts:
  - metadataservice
  location: MESH_EXTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: NONE
{{ end }}