{{- if .Values.settings.egress_aws_enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: aws
spec:
  hosts:
  {{- range .Values.settings.egress_aws_bucket_values }}
  - {{ . }}
  {{- end }}   
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
{{ end }} 

