{{- if .Values.settings.egress_mutual_gateways_enabled }}
  {{- range $k, $v := .Values.settings.egress_mutual_gateways_values }}
    {{- range $kk, $vv := $v }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
  name: {{ $kk }}-ext
spec:
  host: {{ (split "|" $vv)._0 }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: {{ (split "|" $vv)._1 }}
      tls:
        credentialName: {{ (split "|" $vv)._2 }}
        mode: MUTUAL
        sni: {{ (split "|" $vv)._0 }}
---  
    {{ end }}
  {{ end }}
{{- end }}