apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app: istio-ingressgateway-{{ .Values.settings.namespace }}
    istio: ingressgateway-{{ .Values.settings.namespace }}
    istio.io/rev: default
    release: istio
  name: ingressgateway-{{ .Values.settings.namespace }}-service-account
  namespace: "{{ .Values.settings.namespace }}"
secrets:
- name: ingressgateway-{{ .Values.settings.namespace }}-service-account-token-jc9zm
