{{- if .Values.settings.egress_gateway_infrastructure_enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  labels:
    istio.io/rev: default
    release: istio
  name: egressgateway-{{ .Values.settings.namespace }}-sds
  namespace: {{ .Values.settings.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
{{- end }}