{{- if .Values.settings.egress_gateway_infrastructure_enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  labels:
    istio.io/rev: default
    release: istio
  name: egressgateway-{{ .Values.settings.namespace }}-sds
  namespace: {{ .Values.settings.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: egressgateway-{{ .Values.settings.namespace }}-sds
subjects:
- kind: ServiceAccount
  name: egressgateway-{{ .Values.settings.namespace }}-service-account
{{- end }}