{{- if .Values.settings.egress_gateway_infrastructure_enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app: istio-egressgateway-{{ .Values.settings.namespace }}
    istio: egressgateway-{{ .Values.settings.namespace }}
    istio.io/rev: default
    release: istio
  name: egressgateway-{{ .Values.settings.namespace }}-service-account
  namespace: "{{ .Values.settings.namespace }}"
secrets:
- name: egressgateway-{{ .Values.settings.namespace }}-service-account-token-spg9w
{{- end }}