{{- if .Values.settings.egress_gateway_infrastructure_enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: istio-egressgateway-{{ .Values.settings.namespace }}
    istio: egressgateway-{{ .Values.settings.namespace }}
    istio.io/rev: default
    release: istio
    gateway-name: egressgateway-{{ .Values.settings.namespace }}
  name: egressgateway-{{ .Values.settings.namespace }}
  namespace: "{{ .Values.settings.namespace }}"
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: tls
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-egressgateway-{{ .Values.settings.namespace }}
    istio: egressgateway-{{ .Values.settings.namespace }}
  sessionAffinity: None
  type: ClusterIP
status:
{{- end }}