{{- if .Values.settings.egress_simple_gateways_enabled }}
  {{- range $k, $v := .Values.settings.egress_simple_gateways_values }}
    {{- range $kk, $vv := $v }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
  labels:
  name: {{ (split "|" $vv)._2 }}
spec:
  backendType: secretsManager
  data:
  - key: {{ (split "|" $vv)._2 }}-ca
    name: ca.crt
---  
    {{ end }}
  {{ end }}
{{- end }}