{{- if .Values.settings.mesh_policy }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: {{ .Values.settings.mesh_policy }}
{{- end }}    
