{{- if .Values.settings.egress_database_ca_secret_enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  annotations:
  labels:
  name: {{ .Values.settings.egress_database_ca_secret_name }}-ca
spec:
  backendType: secretsManager
  data:
  - key: {{ .Values.settings.egress_database_ca_secret_name }}-ca
    name: ca.crt
{{- end }}
