{{- if .Values.settings.egress_passthrough_enabled }}
  {{- range $k, $v := .Values.settings.egress_passthrough_values }}
    {{- range $kk, $vv := $v }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $kk }}
spec:
  hosts:
  - {{ (split "|" $vv)._0 }}
  ports:
  - number: {{ (split "|" $vv)._1 }}
    name: tls
    protocol: TLS
  resolution: DNS
---  
    {{ end }}
  {{ end }}
{{- end }}