apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  generation: 1
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Base
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.0
    release: istio
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app: {}
          f:chart: {}
          f:heritage: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
      f:spec:
        f:additionalPrinterColumns: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:preserveUnknownFields: {}
        f:scope: {}
        f:validation:
          f:openAPIV3Schema:
            f:properties:
              f:spec:
                .: {}
                f:description: {}
                f:properties:
                  f:metadata:
                    .: {}
                    f:description: {}
                    f:properties:
                      f:annotations:
                        .: {}
                        f:additionalProperties: {}
                        f:type: {}
                      f:labels:
                        .: {}
                        f:additionalProperties: {}
                        f:type: {}
                    f:type: {}
                  f:probe:
                    .: {}
                    f:description: {}
                    f:oneOf: {}
                    f:properties:
                      f:exec:
                        .: {}
                        f:description: {}
                        f:properties:
                          f:command:
                            .: {}
                            f:description: {}
                            f:items: {}
                            f:type: {}
                        f:type: {}
                      f:failureThreshold:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                      f:httpGet:
                        .: {}
                        f:properties:
                          f:host:
                            .: {}
                            f:description: {}
                            f:format: {}
                            f:type: {}
                          f:httpHeaders:
                            .: {}
                            f:description: {}
                            f:items: {}
                            f:type: {}
                          f:path:
                            .: {}
                            f:description: {}
                            f:format: {}
                            f:type: {}
                          f:port:
                            .: {}
                            f:description: {}
                            f:type: {}
                          f:scheme:
                            .: {}
                            f:format: {}
                            f:type: {}
                        f:type: {}
                      f:initialDelaySeconds:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                      f:periodSeconds:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                      f:successThreshold:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                      f:tcpSocket:
                        .: {}
                        f:description: {}
                        f:properties:
                          f:host:
                            .: {}
                            f:format: {}
                            f:type: {}
                          f:port:
                            .: {}
                            f:type: {}
                        f:type: {}
                      f:timeoutSeconds:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                    f:type: {}
                  f:template:
                    .: {}
                    f:description: {}
                    f:properties:
                      f:address:
                        .: {}
                        f:format: {}
                        f:type: {}
                      f:labels:
                        .: {}
                        f:additionalProperties: {}
                        f:description: {}
                        f:type: {}
                      f:locality:
                        .: {}
                        f:description: {}
                        f:format: {}
                        f:type: {}
                      f:network:
                        .: {}
                        f:format: {}
                        f:type: {}
                      f:ports:
                        .: {}
                        f:additionalProperties: {}
                        f:description: {}
                        f:type: {}
                      f:serviceAccount:
                        .: {}
                        f:format: {}
                        f:type: {}
                      f:weight:
                        .: {}
                        f:description: {}
                        f:type: {}
                    f:type: {}
                f:type: {}
              f:status:
                .: {}
                f:type: {}
                f:x-kubernetes-preserve-unknown-fields: {}
            f:type: {}
        f:versions: {}
    manager: istio-operator
    operation: Apply
    time: "2021-02-18T22:33:45Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions: {}
    manager: kube-apiserver
    operation: Update
    time: "2021-02-18T22:33:45Z"
  name: workloadgroups.networking.istio.io
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/workloadgroups.networking.istio.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: 'CreationTimestamp is a timestamp representing the server time when
      this object was created. It is not guaranteed to be set in happens-before order
      across separate operations. Clients may not set this value. It is represented
      in RFC3339 form and is in UTC. Populated by the system. Read-only. Null for
      lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata'
    name: Age
    type: date
  conversion:
    strategy: None
  group: networking.istio.io
  names:
    categories:
    - istio-io
    - networking-istio-io
    kind: WorkloadGroup
    listKind: WorkloadGroupList
    plural: workloadgroups
    shortNames:
    - wg
    singular: workloadgroup
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: 'Describes a collection of workload instances. See more details
            at: https://istio.io/docs/reference/config/networking/workload-group.html'
          properties:
            metadata:
              description: Metadata that will be used for all corresponding `WorkloadEntries`.
              properties:
                annotations:
                  additionalProperties:
                    format: string
                    type: string
                  type: object
                labels:
                  additionalProperties:
                    format: string
                    type: string
                  type: object
              type: object
            probe:
              description: '`ReadinessProbe` describes the configuration the user
                must provide for healthchecking on their workload.'
              oneOf:
              - not:
                  anyOf:
                  - required:
                    - httpGet
                  - required:
                    - tcpSocket
                  - required:
                    - exec
              - required:
                - httpGet
              - required:
                - tcpSocket
              - required:
                - exec
              properties:
                exec:
                  description: Health is determined by how the command that is executed
                    exited.
                  properties:
                    command:
                      description: Command to run.
                      items:
                        format: string
                        type: string
                      type: array
                  type: object
                failureThreshold:
                  description: Minimum consecutive failures for the probe to be considered
                    failed after having succeeded.
                  format: int32
                  type: integer
                httpGet:
                  properties:
                    host:
                      description: Host name to connect to, defaults to the pod IP.
                      format: string
                      type: string
                    httpHeaders:
                      description: Headers the proxy will pass on to make the request.
                      items:
                        properties:
                          name:
                            format: string
                            type: string
                          value:
                            format: string
                            type: string
                        type: object
                      type: array
                    path:
                      description: Path to access on the HTTP server.
                      format: string
                      type: string
                    port:
                      description: Port on which the endpoint lives.
                      type: integer
                    scheme:
                      format: string
                      type: string
                  type: object
                initialDelaySeconds:
                  description: Number of seconds after the container has started before
                    readiness probes are initiated.
                  format: int32
                  type: integer
                periodSeconds:
                  description: How often (in seconds) to perform the probe.
                  format: int32
                  type: integer
                successThreshold:
                  description: Minimum consecutive successes for the probe to be considered
                    successful after having failed.
                  format: int32
                  type: integer
                tcpSocket:
                  description: Health is determined by if the proxy is able to connect.
                  properties:
                    host:
                      format: string
                      type: string
                    port:
                      type: integer
                  type: object
                timeoutSeconds:
                  description: Number of seconds after which the probe times out.
                  format: int32
                  type: integer
              type: object
            template:
              description: Template to be used for the generation of `WorkloadEntry`
                resources that belong to this `WorkloadGroup`.
              properties:
                address:
                  format: string
                  type: string
                labels:
                  additionalProperties:
                    format: string
                    type: string
                  description: One or more labels associated with the endpoint.
                  type: object
                locality:
                  description: The locality associated with the endpoint.
                  format: string
                  type: string
                network:
                  format: string
                  type: string
                ports:
                  additionalProperties:
                    type: integer
                  description: Set of ports associated with the endpoint.
                  type: object
                serviceAccount:
                  format: string
                  type: string
                weight:
                  description: The load balancing weight associated with the endpoint.
                  type: integer
              type: object
          type: object
        status:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      type: object
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
status:
