apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.0
    release: istio
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app: {}
          f:install.operator.istio.io/owning-resource: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
      f:spec:
        f:selector:
          f:matchLabels:
            f:istio: {}
        f:strategy:
          f:rollingUpdate:
            f:maxSurge: {}
            f:maxUnavailable: {}
        f:template:
          f:metadata:
            f:annotations:
              f:prometheus.io/port: {}
              f:prometheus.io/scrape: {}
              f:sidecar.istio.io/inject: {}
            f:labels:
              f:app: {}
              f:install.operator.istio.io/owning-resource: {}
              f:istio: {}
              f:istio.io/rev: {}
              f:operator.istio.io/component: {}
              f:sidecar.istio.io/inject: {}
          f:spec:
            f:containers:
              k:{"name":"discovery"}:
                .: {}
                f:args: {}
                f:env:
                  k:{"name":"CLUSTER_ID"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"EXTERNAL_ISTIOD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"ISTIOD_ADDR"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"JWT_POLICY"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"KUBECONFIG"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PILOT_CERT_PROVIDER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PILOT_ENABLE_ANALYSIS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PILOT_TRACE_SAMPLING"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"POD_NAME"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      f:fieldRef:
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"POD_NAMESPACE"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      f:fieldRef:
                        f:apiVersion: {}
                        f:fieldPath: {}
                  k:{"name":"REVISION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"SERVICE_ACCOUNT"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      f:fieldRef:
                        f:apiVersion: {}
                        f:fieldPath: {}
                f:image: {}
                f:name: {}
                f:ports:
                  k:{"containerPort":8080,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                  k:{"containerPort":15010,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                  k:{"containerPort":15017,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:readinessProbe:
                  f:httpGet:
                    f:path: {}
                    f:port: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:timeoutSeconds: {}
                f:resources:
                  f:requests:
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  f:capabilities:
                    f:drop: {}
                  f:runAsGroup: {}
                  f:runAsNonRoot: {}
                  f:runAsUser: {}
                f:volumeMounts:
                  k:{"mountPath":"/etc/cacerts"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/etc/istio/config"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/lib/istio/inject"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/var/run/secrets/istio-dns"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/var/run/secrets/remote"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
                  k:{"mountPath":"/var/run/secrets/tokens"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:securityContext:
              f:fsGroup: {}
            f:serviceAccountName: {}
            f:volumes:
              k:{"name":"cacerts"}:
                .: {}
                f:name: {}
                f:secret:
                  f:optional: {}
                  f:secretName: {}
              k:{"name":"config-volume"}:
                .: {}
                f:configMap:
                  f:name: {}
                f:name: {}
              k:{"name":"inject"}:
                .: {}
                f:configMap:
                  f:name: {}
                f:name: {}
              k:{"name":"istio-kubeconfig"}:
                .: {}
                f:name: {}
                f:secret:
                  f:optional: {}
                  f:secretName: {}
              k:{"name":"istio-token"}:
                .: {}
                f:name: {}
                f:projected:
                  f:sources: {}
              k:{"name":"local-certs"}:
                .: {}
                f:emptyDir:
                  f:medium: {}
                f:name: {}
    manager: istio-operator
    operation: Apply
    time: "2021-02-18T02:57:02Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-18T02:57:05Z"
  name: istiod
  namespace: istio-system
  selfLink: /apis/apps/v1/namespaces/istio-system/deployments/istiod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      istio: pilot
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: istiod
        install.operator.istio.io/owning-resource: unknown
        istio: pilot
        istio.io/rev: default
        operator.istio.io/component: Pilot
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - discovery
        - --monitoringAddr=:15014
        - --log_output_level=default:info
        - --domain
        - cluster.local
        - --keepaliveMaxServerConnectionAge
        - 30m
        env:
        - name: REVISION
          value: default
        - name: JWT_POLICY
          value: third-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: KUBECONFIG
          value: /var/run/secrets/remote/config
        - name: PILOT_TRACE_SAMPLING
          value: "1"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
          value: "true"
        - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
          value: "true"
        - name: ISTIOD_ADDR
          value: istiod.istio-system.svc:15012
        - name: PILOT_ENABLE_ANALYSIS
          value: "false"
        - name: CLUSTER_ID
          value: Kubernetes
        - name: EXTERNAL_ISTIOD
          value: "false"
        image: docker.repo.bendigobank.com.au/istio/pilot:1.9.0
        imagePullPolicy: Always
        name: discovery
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 15010
          protocol: TCP
        - containerPort: 15017
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsGroup: 1337
          runAsNonRoot: true
          runAsUser: 1337
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/istio/config
          name: config-volume
        - mountPath: /var/run/secrets/tokens
          name: istio-token
          readOnly: true
        - mountPath: /var/run/secrets/istio-dns
          name: local-certs
        - mountPath: /etc/cacerts
          name: cacerts
          readOnly: true
        - mountPath: /var/run/secrets/remote
          name: istio-kubeconfig
          readOnly: true
        - mountPath: /var/lib/istio/inject
          name: inject
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: {{ .Values.settings.host_network }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
      serviceAccount: istiod-service-account
      serviceAccountName: istiod-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: local-certs
      - name: istio-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 43200
              path: istio-token
      - name: cacerts
        secret:
          defaultMode: 420
          optional: true
          secretName: cacerts
      - name: istio-kubeconfig
        secret:
          defaultMode: 420
          optional: true
          secretName: istio-kubeconfig
      - configMap:
          defaultMode: 420
          name: istio-sidecar-injector
        name: inject
      - configMap:
          defaultMode: 420
          name: istio
        name: config-volume
status:
