apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
  generation: 1
  labels:
    app: istiod
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: pilot
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.0
    release: istio
  managedFields:
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app: {}
          f:install.operator.istio.io/owning-resource: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
      f:spec:
        f:minAvailable: {}
        f:selector:
          f:matchLabels:
            f:app: {}
            f:istio: {}
    manager: istio-operator
    operation: Apply
    time: "2021-02-18T02:57:02Z"
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:currentHealthy: {}
        f:desiredHealthy: {}
        f:expectedPods: {}
        f:observedGeneration: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-18T02:57:05Z"
  name: istiod
  namespace: istio-system
  selfLink: /apis/policy/v1beta1/namespaces/istio-system/poddisruptionbudgets/istiod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istiod
      istio: pilot
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
