apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app: istiod
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Base
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.9.0
    release: istio
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          f:app: {}
          f:install.operator.istio.io/owning-resource-namespace: {}
          f:istio.io/rev: {}
          f:operator.istio.io/component: {}
          f:operator.istio.io/managed: {}
          f:operator.istio.io/version: {}
          f:release: {}
    manager: istio-operator
    operation: Apply
    time: "2021-02-18T02:56:57Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:secrets:
        .: {}
        k:{"name":"istiod-service-account-token-h7jgd"}:
          .: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-02-18T02:56:57Z"
  name: istiod-service-account
  namespace: istio-system
  selfLink: /api/v1/namespaces/istio-system/serviceaccounts/istiod-service-account
secrets:
- name: istiod-service-account-token-h7jgd
